### PR TITLE
improved svg animation, winking and mustache

### PR DESCRIPTION
**Pull request by tsykora**
Hair static, eyes winking at the end of a read line, mustache "thinking" -- fluent svg animation.

### CODE REVIEW

**Comment by tsykora** [comment]
@marvec take a look and feedback it pls :)

**Comment by livthomas** [comment]
@tsykora, can you show us the picture what it looks like after these changes?

**Comment by tsykora** [comment]
@livthomas it is animation. The fastest way how to see it is to checkout my branch and just open index.html page in the browser. You should see the animated logo then.

**Comment by livthomas** [comment]
The web looks much different now. But we will use this animation (after some modifications) on the loading page of our application.

**Pull request closed without merging**
